### ISSUE TITLE
Something with resin

### ISSUE THREAD

**Issue by LatentDesire1** [cybercat-mods/gigeresque#140]
https://paste.ee/p/oKzQ8

**Comment by ImpulsiveLass** [comment]
I got it too if this helps
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-03-05 22:17:52
Description: Colliding entity with block

java.lang.ClassCastException: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1542 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4d339552)
	at mods.cybercat.gigeresque.common.block.NestResinWebFullBlock.method_9548(NestResinWebFullBlock.java:28)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:983)
	at net.minecraft.class_1297.method_5852(class_1297.java:1063)
	at net.minecraft.class_1297.method_36974(class_1297.java:781)
	at net.minecraft.class_1297.method_5784(class_1297.java:750)
	at net.minecraft.class_1542.method_5773(class_1542.java:130)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mods.cybercat.gigeresque.common.block.NestResinWebFullBlock.method_9548(NestResinWebFullBlock.java:28)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:983)
	at net.minecraft.class_1297.method_5852(class_1297.java:1063)
	at net.minecraft.class_1297.method_36974(class_1297.java:781)
	at net.minecraft.class_1297.method_5784(class_1297.java:750)
	at net.minecraft.class_1542.method_5773(class_1542.java:130)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)

-- Block being collided with --
Details:
	Block: Block{gigeresque:nest_resin_web_cross}
	Block location: World: (206,88,-60), Section: (at 14,8,4 in 12,5,-4; chunk contains blocks 192,-64,-64 to 207,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.class_1297.method_5852(class_1297.java:1063)
	at net.minecraft.class_1297.method_36974(class_1297.java:781)
	at net.minecraft.class_1297.method_5784(class_1297.java:750)
	at net.minecraft.class_1542.method_5773(class_1542.java:130)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 8202
	Entity Name: White Wool
	Entity's Exact location: 206.42, 88.16, -59.44
	Entity's Block location: World: (206,88,-60), Section: (at 14,8,4 in 12,5,-4; chunk contains blocks 192,-64,-64 to 207,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: -0.08, 0.16, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_36974(class_1297.java:781)
	at net.minecraft.class_1297.method_5784(class_1297.java:750)
	at net.minecraft.class_1542.method_5773(class_1542.java:130)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 8202
	Entity Name: White Wool
	Entity's Exact location: 206.42, 88.16, -59.44
	Entity's Block location: World: (206,88,-60), Section: (at 14,8,4 in 12,5,-4; chunk contains blocks 192,-64,-64 to 207,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: -0.08, 0.16, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['ImpulsiveLad0955'/2378, l='ClientLevel', x=178.44, y=89.12, z=-109.04]]
	Chunk stats: 4096, 1025
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,104,32), Section: (at 0,8,0 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 9272 game time, 5156 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, essential

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3506076904 bytes (3343 MiB) / 13824425984 bytes (13184 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.7019
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75195.73
	Virtual memory used (MB): 29574.80
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 1.34
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.1
		architectury: Architectury 7.1.70
		axesareweapons: Axes Are Weapons 1.6.5
		azurelib: AzureLib 1.0.2
			com_eliotlash_mclib_mclib: mclib 20
		badpackets: Bad Packets 0.3.4
		bclib: BCLib 2.2.4
		betterdeserttemples: YUNG's Better Desert Temples 1.19.3-Fabric-2.3.0
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.3-Fabric-3.3.0
		betterend: Better End 3.1.2
		betterfortresses: YUNG's Better Nether Fortresses 1.19.3-Fabric-1.1.0
		bettermineshafts: YUNG's Better Mineshafts 1.19.3-Fabric-3.3.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.3-Fabric-2.2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.3-Fabric-3.3.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.3-Fabric-2.2.0
		cinderscapes: Cinderscapes 3.1.0
			cinderscapes-client: Cinderscapes: Client 3.1.0
			cinderscapes-common: Cinderscapes: Common 3.1.0
			cinderscapes-worldgen: Cinderscapes: World Generation 3.1.0
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 5.0.0-beta.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 5.0.0-beta.1
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		dashloader: DashLoader 5.0.0-alpha.9+1.19.3
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.2
			dev_quantumfusion_taski: Taski 2.1.0
		dawn: Dawn API 4.1.1
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		elementa: Elementa 575
		endrem: End Remastered 5.2.1
		essential: Essential 11903+deploy-staging+g9cc271010
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.4
		fabric-api: Fabric API 0.75.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.1+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.1+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.44+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.10+312c329485
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.12+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.20+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.24+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.31+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.1+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.30+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.33+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+eb2a3ba985
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.5+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		fallingtree: FallingTree 3.11.2
		fastload: Fast Load 2.6.11
		friendsandfoes: Friends&Foes 1.7.5
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		fromanotherworld: From Another World 1.0.1
		geckolib: Geckolib 4.0.3
		gigeresque: Gigeresque 0.5.14
		graveyard: The Graveyard 2.5
			omega-config: OmegaConfig 1.2.2-1.18.1
		hwg: Happiness is a Warm Gun 1.3.3
		incendium: Incendium 5.1.4
		inventoryprofilesnext: Inventory Profiles Next 1.9.2
		jade: Jade 9.3.1
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.3
			journeymap-api-fabric: JourneyMap API 1.19.3-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.3
			pride: Pride Lib 1.2.0+1.19.3
			spruceui: SpruceUI 4.1.0+1.19.3
		libipn: libIPN 2.0.2
		lithium: Lithium 0.10.4
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		mob_captains_mr: Mob Captains 1-v2.1.0
		modmenu: Mod Menu 5.0.2
		moremobvariants: More Mob Variants 1.0.1
		nullscape: Nullscape 1.2
		org_jetbrains_annotations: annotations 13.0
		plentyofarmors: Plenty Of Armors 1.1.1
		promenade: Promenade 3.1.0
		roughlyenoughitems: Roughly Enough Items 10.0.592
			error_notifier: Error Notifier 1.0.9
		smartbrainlib: SmartBrainLib 1.8
		sodium: Sodium 0.4.9+build.23
		sound_physics_remastered: Sound Physics Remastered 1.19.3-1.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		stoneholm: Stoneholm 1.4.4
		terrestria: Terrestria 5.1.1
			terrablender: TerraBlender 2.1.0.132
				com_electronwill_night-config_core: core 3.6.4
				com_electronwill_night-config_toml: toml 3.6.4
			terraform-config-api-v1: Terraform Config API (v1) 5.0.0-beta.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 5.0.0-beta.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 5.0.0-beta.1
			terraform-tree-api-v1: Terraform Tree API (v1) 5.0.0-beta.1
			terrestria-client: Terrestria: Client 5.1.1
			terrestria-common: Terrestria: Common 5.1.1
			terrestria-worldgen: Terrestria: World Generation 5.1.1
		universalcraft: UniversalCraft 254
		vigilance: Vigilance 278
		visuality: Visuality 0.6.0
		waterdripsound: Drip Sounds 1.19-0.3.1
		wildfire_gender: Wildfire's Female Gender Mod 1.19.3-3.0.1
		yungsapi: YUNG's API 1.19.3-Fabric-3.9.0
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.3-Fabric-3.2.0
		yungsextras: YUNG's Extras 1.19.3-Fabric-3.2.0
	Launched Version: fabric-loader-0.14.14-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.0 Core Profile Context 22.11.1.221110, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['ImpulsiveLad0955'/2378, l='ServerLevel[New World]', x=178.44, y=89.12, z=-109.04]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
