### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by ghost** [cybercat-mods/gigeresque#153]
I used just the mod and the mods that needs and it crashes when i get to the dungeon

**Comment by AzureDoom** [comment]
You'll need to provide a proper crash log.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
Time: 2023-04-05 15:38:06
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot read field "field_1687" because "this.minecraft" is null
	at mod.azure.azurelib.renderer.layer.BlockAndItemGeoLayer.renderStackForBone(BlockAndItemGeoLayer.java:124)
	at mods.cybercat.gigeresque.client.entity.render.blocks.SittingIdolRender$1.renderStackForBone(SittingIdolRender.java:44)
	at mods.cybercat.gigeresque.client.entity.render.blocks.SittingIdolRender$1.renderStackForBone(SittingIdolRender.java:22)
	at mod.azure.azurelib.renderer.layer.BlockAndItemGeoLayer.renderForBone(BlockAndItemGeoLayer.java:101)
	at mod.azure.azurelib.renderer.GeoRenderer.applyRenderLayersForBone(GeoRenderer.java:188)
	at mod.azure.azurelib.renderer.GeoRenderer.renderRecursively(GeoRenderer.java:228)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:180)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.renderChildBones(GeoRenderer.java:259)
	at mod.azure.azurelib.renderer.GeoRenderer.renderRecursively(GeoRenderer.java:230)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:180)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.actuallyRender(GeoRenderer.java:167)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.actuallyRender(GeoBlockRenderer.java:158)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.actuallyRender(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:135)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.method_3569(GeoBlockRenderer.java:129)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.minecraft.class_761.method_22710(class_761.java:1365)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.azure.azurelib.renderer.layer.BlockAndItemGeoLayer.renderStackForBone(BlockAndItemGeoLayer.java:124)
	at mods.cybercat.gigeresque.client.entity.render.blocks.SittingIdolRender$1.renderStackForBone(SittingIdolRender.java:44)
	at mods.cybercat.gigeresque.client.entity.render.blocks.SittingIdolRender$1.renderStackForBone(SittingIdolRender.java:22)
	at mod.azure.azurelib.renderer.layer.BlockAndItemGeoLayer.renderForBone(BlockAndItemGeoLayer.java:101)
	at mod.azure.azurelib.renderer.GeoRenderer.applyRenderLayersForBone(GeoRenderer.java:188)
	at mod.azure.azurelib.renderer.GeoRenderer.renderRecursively(GeoRenderer.java:228)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:180)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.renderChildBones(GeoRenderer.java:259)
	at mod.azure.azurelib.renderer.GeoRenderer.renderRecursively(GeoRenderer.java:230)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:180)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.renderRecursively(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.actuallyRender(GeoRenderer.java:167)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.actuallyRender(GeoBlockRenderer.java:158)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.actuallyRender(GeoBlockRenderer.java:35)
	at mod.azure.azurelib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:135)
	at mod.azure.azurelib.renderer.GeoBlockRenderer.method_3569(GeoBlockRenderer.java:129)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.minecraft.class_761.method_22710(class_761.java:1365)
	at net.minecraft.class_757.method_3188(class_757.java:1100)

-- Block Entity Details --
Details:
	Name: gigeresque:sitting_idol_entity // mods.cybercat.gigeresque.common.block.entity.IdolStorageEntity
	Block: Block{gigeresque:alien_storage_block3}[facing=south,storage_state=closed]
	Block location: World: (-8637,-11,-997), Section: (at 3,5,11 in -540,-1,-63; chunk contains blocks -8640,-64,-1008 to -8625,319,-993), Region: (-17,-2; contains chunks -544,-64 to -513,-33, blocks -8704,-64,-1024 to -8193,319,-513)
	Block: Block{gigeresque:alien_storage_block3}[facing=south,storage_state=closed]
	Block location: World: (-8637,-11,-997), Section: (at 3,5,11 in -540,-1,-63; chunk contains blocks -8640,-64,-1008 to -8625,319,-993), Region: (-17,-2; contains chunks -544,-64 to -513,-33, blocks -8704,-64,-1024 to -8193,319,-513)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at net.minecraft.class_761.method_22710(class_761.java:1365)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by AzureDoom** [comment]
What is your azurelib version?

**Comment by ghost** [comment]
1.0.6

**Comment by AzureDoom** [comment]
Which MC version?

**Comment by ghost** [comment]
1.19.4

**Comment by AzureDoom** [comment]
Then you need to update Azurelib.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
thank you
