### ISSUE TITLE
Crash on server Fabric 1.20.1 v0.5.71

### ISSUE THREAD

**Issue by AlanCataldo** [cybercat-mods/gigeresque#281]
Here is the error message when one of your entity try to load :

net.minecraft.server.TickTask.runTickTask: Ticking entity
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:901) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTasks(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.startServer(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.Entity.tick()" because "entity" is null
        at net.minecraft.entity.Entity.handler$cgi000$gigeresque$tick(Entity.java:1201) ~[server-intermediary.jar:?]
        at net.minecraft.entity.Entity.tick(Entity.java) ~[server-intermediary.jar:?]
        at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:494) ~[server-intermediary.jar:?]
        at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:489) ~[server-intermediary.jar:?]
        at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:700) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:402) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity.java:344) ~[server-intermediary.jar:?]
        at net.minecraft.entity.Entity.tick(Entity.java:271) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerWorld.tickEntities(ServerWorld.java:739) ~[server-intermediary.jar:?]
        at net.minecraft.world.World.tickEntity(World.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.world.entity.EntityHandler.tick(EntityHandler.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        ... 5 more

**Comment by AzureDoom** [comment]
1.20.1 is not supported or updated anymore
