### ISSUE TITLE
I can't spawn the face hugger and when the egg opens it crashes my game

### ISSUE THREAD

**Issue by Virtulzx** [cybercat-mods/gigeresque#291]
I have no idea what i should show here but please remove the ticking entity out of my game please
 ---- Minecraft Crash Report ----
// My bad.

Time: 2024-09-11 21:10:46
Description: Ticking entity

java.lang.IllegalStateException: Entity class mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity has not defined synched data value 29
	at net.minecraft.class_2945$class_9222.method_56911(class_2945.java:231)
	at net.minecraft.class_1297.<init>(class_1297.java:310)
	at net.minecraft.class_1309.<init>(class_1309.java:270)
	at net.minecraft.class_1308.<init>(class_1308.java:148)
	at net.minecraft.class_1314.<init>(class_1314.java:17)
	at net.minecraft.class_1588.<init>(class_1588.java:31)
	at mods.cybercat.gigeresque.common.entity.AlienEntity.<init>(AlienEntity.java:102)
	at mods.azure.bettercrawling.CrawlerMonsterEntity.<init>(CrawlerMonsterEntity.java:129)
	at mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity.<init>(FacehuggerEntity.java:96)
	at net.minecraft.class_1299.method_5883(class_1299.java:552)
	at mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity.method_5773(AlienEggEntity.java:204)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2945$class_9222.method_56911(class_2945.java:231)
	at net.minecraft.class_1297.<init>(class_1297.java:310)
	at net.minecraft.class_1309.<init>(class_1309.java:270)
	at net.minecraft.class_1308.<init>(class_1308.java:148)
	at net.minecraft.class_1314.<init>(class_1314.java:17)
	at net.minecraft.class_1588.<init>(class_1588.java:31)
	at mods.cybercat.gigeresque.common.entity.AlienEntity.<init>(AlienEntity.java:102)
	at mods.azure.bettercrawling.CrawlerMonsterEntity.<init>(CrawlerMonsterEntity.java:129)
	at mods.cybercat.gigeresque.common.entity.impl.classic.FacehuggerEntity.<init>(FacehuggerEntity.java:96)
	at net.minecraft.class_1299.method_5883(class_1299.java:552)
	at mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity.method_5773(AlienEggEntity.java:204)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: gigeresque:egg (mods.cybercat.gigeresque.common.entity.impl.classic.AlienEggEntity)
	Entity ID: 8
	Entity Name: Alien Egg
	Entity's Exact location: -9.50, 69.00, 25.50
	Entity's Block location: World: (-10,69,25), Section: (at 6,5,9 in -1,4,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,32), Section: (at 0,0,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 244 game time, 244 day time
	Level name: New Worldasfsdfdsf
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 110543 (now: false), thunder time: 47213 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 10
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 117868504 bytes (112 MiB) / 685768704 bytes (654 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500                               
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5123
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34605.88
	Virtual memory used (MiB): 12842.18
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 31.85
	Space in storage for jna.tmpdir (MiB): available: 1477109.25, total: 1906893.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1477109.25, total: 1906893.00
	Space in storage for io.netty.native.workdir (MiB): available: 1477109.25, total: 1906893.00
	Space in storage for java.io.tmpdir (MiB): available: 1477109.25, total: 1906893.00
	Space in storage for workdir (MiB): available: 1477109.25, total: 1906893.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		azurelib: AzureLib 2.3.19
		azurelibarmor: AzureLib Armor 2.3.4
		azurepaxels: Azure Paxels 1.0.4
		fabric-api: Fabric API 0.104.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.22+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.7.0+4053855719
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.19+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.2.0+d38f898f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		gigeresque: Gigeresque 0.6.11
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
	Server Running: true
	Player Count: 0 / 8; []
	Active Data Packs: vanilla, fabric, azurepaxels (incompatible), fabric-convention-tags-v2, gigeresque (incompatible)
	Available Data Packs: azurepaxels (incompatible), bundle, fabric, fabric-convention-tags-v2, gigeresque (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 3358035101928315849
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.5-1.21.1

**Comment by AzureDoom** [comment]
Please provide a full next time, to ensure you are on the correct version.
